# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a517a66d2c10effb15f57c599437d471629b5d730038d66b192ed0c5f1ded68c072905b75c29ac66204b24a10d2a2ebc8cfc45310401eb9034b7ad714b5a927

test:
  secret_key_base: 56c1525b47624da53d3654522171b67fb8d8efb0ab6e7fb3cc1a3b041e9e116428240067b6a39f056b4d9082d4d7aa8bad335b873956e4c09ef285df38df9f0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
